{% set python_min = "3.10" %}
{% set name = "inequality" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a093aa58effc26a9152b021a02330be3b184053f5c1c35152c725f022c50395b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - libpysal >=4.5
    - scipy >=1.8
    - numpy >=1.23

test:
  requires:
    - python {{ python_min }}
  imports:
    - inequality

about:
  home: https://github.com/pysal/inequality
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Spatial inequality analysis for PySAL A library of spatial analysis functions.'
  description: |
    Spatial inequality analysis for PySAL A library of spatial analysis functions.
  doc_url: https://pysal.org/inequality
  dev_url: https://github.com/pysal/inequality/

extra:
  recipe-maintainers:
    - martinfleis
    - jGaboardi
    - knaaptime
    - sjsrey
