{% set python_min = "3.12" %}
{% set name = "inequality" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acdfb22513cf278ee273942d71e0a6a1ba40e1da4a9e0a657cb1a032df3eb646

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - libpysal >=4.12
    - matplotlib-base >=3.10
    - numpy >=2
    - pandas >=2.3
    - scipy >=1.14
    - tqdm
    - joblib

test:
  requires:
    - python {{ python_min }}
  imports:
    - inequality

about:
  home: https://github.com/pysal/inequality
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Spatial inequality analysis for PySAL A library of spatial analysis functions.'
  description: |
    Spatial inequality analysis for PySAL A library of spatial analysis functions.
  doc_url: https://pysal.org/inequality
  dev_url: https://github.com/pysal/inequality/

extra:
  recipe-maintainers:
    - martinfleis
    - jGaboardi
    - knaaptime
    - sjsrey
